<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Title>ZSecurity</Title>
		<Authors>Ricardo Zambon</Authors>
		<Company>ZambonSoft</Company>
		<Version>1.0.0</Version>
		<PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
		<PackageTags>security;authorization;permissions</PackageTags>
		<RepositoryUrl>https://github.com/RicardoZambon/ZSecurity</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<Description>ZSecurity is a library that brings additional functionalities for handling security.</Description>
		<Copyright>ZambonSoft</Copyright>
		<PackageProjectUrl>https://github.com/RicardoZambon/ZSecurity</PackageProjectUrl>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ZDatabase" Version="1.6.0" />
	</ItemGroup>

</Project>
